#!/bin/bash

cd ..

# Set default values for options
mode="both"
split_ratio=10

# Parse command line options
while getopts "f:q:g:m:r:" opt; do
  case ${opt} in
    f ) fasta_input=$OPTARG;;
    q ) fastq_input=$OPTARG;;
    g ) gff_input=$OPTARG;;
    m ) mode=$OPTARG;;
    r ) split_ratio=$OPTARG;;
    \? ) echo "Invalid option: -$OPTARG" 1>&2; exit 1;;
    : ) echo "Option -$OPTARG requires an argument." 1>&2; exit 1;;
  esac
done

# Display warning message if -m option is not provided
if [ "$mode" == "both" ]
then
  echo ""
  echo "Warning: -m option not specified. Using default option, both Non-contiguous operons and excludons will be identified. To select only one of the available options, please specify either -m Operon or -m Excludon"
  echo ""
fi

# Check that mandatory input files are specified
if [ -z "$fasta_input" ] || [ -z "$fastq_input" ] || [ -z "$gff_input" ]
then
  echo ""
  echo "Usage: $0 -f <fasta_input> -q <fastq_input> -g <gff_input> [-m mode] [-r split ratio]" 1>&2
  echo "Mandatory input files are missing. Please provide the required inputs: -f, -q, and -g" 1>&2
  echo ""
  exit 1
fi


## Replace ID for gene_id if neccessary. gff file from NCBI is annotated as ID but the hole script uses the gene_id annotation
sed -i 's/ID/gene_id/g' $gff_input

echo "################ MAKNG ALIGMENT #####################"



filename=$(basename "$fastq_input")   # Extract the filename from the path
sample=${filename%.fastq}        # Remove the .fastq extension and extract the word before it


mkdir -p results/minimap

minimap2 -p 0.99 -ax splice -k14 --MD -uf \
  $fasta_input \
  $fastq_input| \
  samtools sort -O bam - > results/minimap/${sample}_sorted.bam
 
samtools index results/minimap/${sample}_sorted.bam
echo "$sample"


echo " ### DONE ### "
echo "################ GET DEPTH AT EACH POSITION IN THE GENOME #####################"

mkdir -p results/coverage_data


samtools view -F 0x10 -h -b results/minimap/${sample}_sorted.bam | \
  samtools depth -a -d 0 -o results/coverage_data/${sample}_plus_depth.txt -
echo ". . . "

samtools view -f 0x10 -h -b results/minimap/${sample}_sorted.bam | \
  samtools depth -a -d 0 -o results/coverage_data/${sample}_minus_depth.txt -
 
 echo " ### DONE ### "
bam="results/minimap/${sample}_sorted.bam"

echo "$bam"
echo " ################## GET COUNTS OF MAPPED READS ######################## " 
mkdir -p results/operons

Rscript Scripts/overlapping_reads.R $fasta_input  $gff_input $bam  $sample $mode $split_ratio
  
echo "### The analysis is finished ###"

